### ISSUE TITLE
mobile - case: all cases look weird on scroll, text starts to high up and cant be read

### ISSUE THREAD

**Issue by oliverjuan** [oakwood/oakwood.se#19]
![Skärmavbild 2019-12-16 kl. 11.10.03.png](https://images.zenhubusercontent.com/5bb5c0cd0da5e036419a0f0a/33269b49-2fb9-49fb-bfa6-61785a214bed)

**Comment by belluede** [comment]
@Leolainen Needs to be fine-tuned for mobile
