### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by belluede** [oakwood/oakwood.se#37]
@koelare please provide ahmed with a favicon

**Comment by AhmedAbdulrahman** [comment]
Tested on Chrome, Safari, Firefox, Anroid (Chrome, Firefox) all works @belluede 
![Screenshot 2020-02-21 at 10 58 54](https://user-images.githubusercontent.com/10485129/75024202-55891c80-5499-11ea-844e-35a8e275fba0.png)
![Screenshot 2020-02-21 at 10 58 02](https://user-images.githubusercontent.com/10485129/75024207-56ba4980-5499-11ea-89ec-fe79c9271aa4.png)
![Screenshot 2020-02-21 at 10 57 52](https://user-images.githubusercontent.com/10485129/75024208-5752e000-5499-11ea-95c2-191e027a3f42.png)

![Screenshot 2020-02-21 at 11 02 31](https://user-images.githubusercontent.com/10485129/75024480-c0d2ee80-5499-11ea-976f-16a504d7b811.png)

![Screenshot 2020-02-21 at 11 04 56](https://user-images.githubusercontent.com/10485129/75024650-13aca600-549a-11ea-8428-fbfdb406606c.png)
