### ISSUE TITLE
Hero Block: Support transparent PNGs on the blocks

### ISSUE THREAD

**Issue by belluede** [oakwood/oakwood.se#51]

**Comment by alexanderflink** [comment]
It's not possible to overlay transparent textures on the model without resorting to unnecessary performance heavy solutions. The same effect can be achieved by saving the image as a JPG with the same background color as the blocks. Example at https://beta.oakwood.se/

**Comment by belluede** [comment]
@koelare See above.

**Comment by belluede** [comment]
@koelare please provide the eytys & fjällräven logos as JPG when you have time
